version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjsdb
      POSTGRES_USER: user
    volumes:
      - ./db-data-postgres:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
    volumes:
      - ./db-data-mongodb:/data/db
